spring.application.name=backend
# ===============================
# 1. CONFIGURACI�N H2 (MODO MYSQL)
# ===============================
# Crea el archivo local "mercado_db" en la ra�z de tu carpeta backend
spring.datasource.url=jdbc:h2:file:./mercado_db;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# 2. CONFIGURACI�N JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# "update" lee tus clases Java y crea/actualiza las tablas autom�ticamente
spring.jpa.hibernate.ddl-auto= update
# Muestra las consultas SQL en la consola (s�per �til para debugear)
spring.jpa.show-sql=true

# ===============================
# 3. CONSOLA WEB VISUAL
# ===============================
# Activa la interfaz gr�fica en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console